NOAA-GFDL/fre-cli

- meta.yaml
Add pyyaml and jsonschema as conda prereqs, and change package name to fre-cli.
The tools will still be available as fre (fre --help).
> small meta.yaml updates

- fre/frepp/configureScriptXML.py
The current check is not portable and fails on gaea.
> fre pp convert: Remove unneeded check for PATH.

- fre/fre.py
- fre/frepp/checkoutScript.py
- fre/frepp/frepp.py
- Updated --help in fre, frepp, checkoutScript; if it's too long, I can shorten
- Slightly clearer errors on checkoutScript for the git clone
- CheckoutScript: more imports, slightly changed format of the subprocess command for error-checking within the script rather than exiting
Scripted tests: /home/cew/Code/fre-features/fre2_branch_clone/test_fre2_branch_clone.bash
> 61.branch.clone

- fre/frepp/configureScriptYAML.py
- fre/frepp/ppyaml_test/pp.yaml
I was accidentally making the rose-suite experiment config a directory instead of a file.
>  Fix rose-suite-exp config file creation

- fre/pp/configureScriptYAML.py
- fre/pp/edits-template.yaml
- fre/pp/ppyaml_test/pp.yaml
- fre/pp/schema.json
In the remap-pp-components rewrite, Dana realized the grid value needed to specify default or whatever grid was being used, in the rose-app.conf. This pr is fixing the way `grid` is configured
>  Fix grid value name for remap and regrid rose apps (for now)

- fre/make/createCheckout.py
- previously thought this path check was unnecessary, and that we would re-create checkout script every time
- loop adds in functionality that if checkout script already exists (and works) , users can use that checkout script (they won't have to re-create checkout script)
> Add path checking back in for checkout script

- fre/pp/configure_script_yaml.py
- fre/pp/ppyaml_test/pp.yaml
- fre/pp/schema.json
Minor cleanup:
* use metomi.rose for writing rose config files
* retrieve pathnames from command line arguments instead of pp.yaml
Also simplify some of the pp.yaml component definitions, by removing timeseries and timeaverage tags that are not absolutely needed in canopy.
> PP configure-yaml updates

- fre/make/gfdlfremake/checkout.py
Remove `self.checkoutScript.write(c['additionalInstructions'])` because this step was done previously. This line was redundant and was causing `additionalInstructions` to be written one more time than needed in the checkout script that is created. 
N/A
> Remove extra `write` for `c[additional instructions]`

- .github/workflows/create_test_conda_env.yml
- .github/workflows/publish_conda.yml
- environment.yml
- meta.yaml
updates `environment.yml` to reflect the same dependencies as whats in `meta.yaml`, plus pip.
adds workflow file `create_test_conda_env.yml` to use `environment.yml` to create environment, then uses that environment's python/pip to install `fre-cli` in that environment, and that environment's `pytest` is called to run tests.
`publish_conda.yml`'s job  name is changed to just `publish` from `build_and_publish`, to line up more with the workflow file's name.
#122, #75 
- N/A ~~I wrote a new test, if applicable~~
- N/A ~~I wrote new instructions/documentation, if applicable~~
- N/A ~~I ran pylint and attempted to implement some of it's feedback~~
> Improve ci workflows

- fre/pp/checkoutScript.py
Replaced gitlab checkout with github checkout; fixed bug in checkout that hard-coded branch="main"
- [ x] I ran my code
- [ x] I tried to make my code readable
- [ x] I tried to comment my code
- [ x] I ran pytest and inspected it's output
This probably does deserve a pytest test for teh branch checkout, but that's another to-do item
> switching checkout repo; fixing bug in branch checkout

- .github/workflows/create_test_conda_env.yml
- fre/fre.py
this runs `pylint` as part of the `conda env create` check, in a separate workflow from `conda build` routines. it lets the `pylint` feedback be accessed with a single click- see checks on this PR!
~~- [ ] I tried to comment my code~~
~~- [ ] I wrote a new test, if applicable~~
~~- [ ] I wrote new instructions/documentation, if applicable~~
~~- [ ] I ran pytest and inspected it's output~~
> make `pylint` output more easily accessible in CI/CD

- environment.yml
- fre/catalog/frecatalog.py
- fre/catalog/tests/test_fre_catalog.py
- meta.yaml
- setup.py
`from scripts import gen_intake_gfdl` and similar lines from the old `noaa-gfdl::intakebuilder`. now called `noaa-gfdl::catalogbuilder`. corresponding edits in `meta.yaml`, `setup.py` and `environment.yml` included. new import test line added to `meta.yaml` to check import
#128 
~~- [ ] I wrote new instructions/documentation, if applicable~~
> intakebuilder --> catalogbuilder edits 

- fre/pp/configure_script_yaml.py
`fre pp configure-yaml` was unable to locate the child experiment pp.yaml. An update to prepend the directory containing the main yaml resolves the problem.
#99
> Locate the experiment pp.yamls relative to the main yaml dir

- fre/make/tests/AM5_example/am5.yaml
- fre/make/tests/AM5_example/compile.yaml
- fre/make/tests/AM5_example/platforms.yaml
- fre/make/tests/SHiELD_example/SHiELD.yaml
- fre/make/tests/SHiELD_example/compile.yaml
- fre/make/tests/SHiELD_example/platforms.yaml
Just adding example yamls created for models, for eventual fremake testing AND yaml integration development (ONE model yaml for fremake and pp yamls)
Yaml integration: https://github.com/NOAA-GFDL/fre-cli/issues/141
>  #141 Add example yamls for fremake testing

- .github/workflows/documentation.yml
Our sphinx CI building suddenly stopped working with this error:
Reason: UndefinedError("'style' is undefined")
Others have found that the cause is a mismatch between sphinx and sphinx-rtd-theme, and is fixed by updating the latter.
https://github.com/readthedocs/sphinx_rtd_theme/issues/1571
> upgrade the version of sphinx-rtd-theme to fix "style is undefined"

- fre/make/tests/ESM4_example/compile.yaml
- fre/make/tests/ESM4_example/esm4.yaml
- fre/make/tests/ESM4_example/platforms.yaml
Adds yaml test files for the esm4.2 model xml.
The mom6 additional instructions won't fully work due to variables/properties not being carried over to the shell, but the compile should give you the same executable as the xml without modfications.
#141
> Add fremake test yamls for esm4.2

- fre/tests/test_fre_catalog_cli.py
Previously, the test verified the exit code and message for
(fre-cli) c2b:~/git/fre-cli%>fre catalog builder
No paths given, using yaml configuration
(fre-cli) c2b:~/git/fre-cli%>echo $status
1
Recently, the message was updated to be:
(fre-cli) c2b:~/git/fre-cli%>fre catalog builder 
Missing: input_path or output_path. Pass it in the config yaml or as command-line option
(fre-cli) c2b:~/git/fre-cli%>echo $status 
1
So let's continue to check for the exit code and not require an exact error message.
> Update "fre catalog builder" test after upstream CatalogBuilder change

- fre/yamltools/combine_yamls.py
Just a small fix for the combiner failing when given an absolute path for the yaml input file.
> fix absolute paths for yaml combiner

- fre/catalog/frecatalog.py
- fre/tests/test_fre_catalog_cli.py
Added fre-cli interface (`fre catalog merge`) to catalog combining tool in CatalogBuilder (https://github.com/NOAA-GFDL/CatalogBuilder/blob/main/catalogbuilder/scripts/combine_cats.py)
```
>fre catalog merge --help   
Usage: fre catalog merge [OPTIONS]
- Merge two or more more catalogs into one
Options:
--input TEXT   Catalog json files to be merged, space-separated  [required]
--output TEXT  Merged catalog  [required]
--help         Show this message and exit.
```
```
>fre catalog merge --input ~/catalog/catalog1.json --input ~/catalog/catalog2.json --output mycat
/home/c2b/catalog/catalog1.csv
/home/c2b/catalog/catalog2.csv
INFO: Schema differs
{'catalog_file': '/home/Chris.Blanton/catalog/catalog2.csv'}
We can combine since the catalog_file is the only difference
Combined catalog …
```
> Add click bindings for 'fre catalog merge'

- fre/make/gfdlfremake/buildBaremetal.py
- fre/make/gfdlfremake/checkout.py
- make scripts executable after creating
- moved `chmod` lines earlier in scripts
>  #212 Make compile and checkout scripts executable

- fre/make/gfdlfremake/checkout.py
- fre/make/runFremake.py
Some changes needed to get the run-fremake subcommand working. Just switches around the names for `run_fremake` and adds a chmod.
> update function names for run_fremake subcommand

- fre/make/tests/test_create_makefile.py
- fre/pp/configure_script_yaml.py
- fre/pp/tests/test_configure_script_yaml.py
- fre/yamltools/combine_yamls.py
- fre/yamltools/tests/test_combine_yamls.py
> 223.fre make makefile test

- .github/workflows/build_conda.yml
- .github/workflows/create_test_conda_env.yml
- docs/contributing_to_doc.rst
- docs/developer_usage.rst
- docs/fre_app.rst
- docs/fre_catalog.rst
- docs/fre_cmor.rst
- docs/fre_make.rst
- docs/fre_pp.rst
- docs/fre_yamltools.rst
- docs/usage.rst
`fre cmor` doc updates being pushed to `ilaflott::update-fre-cmor-doc3`. this being cannibalized for useful `include` structure in `reStructuredText`
------------------------
~~focusing on `fre cmor` functionality here more explicitly, having lopped off #254 after some good general changes.~~
see preview of doc page at my [fork's gh-pages](https://ilaflott.github.io/ians_fre_cli/)
> basic doc updates 

- .github/workflows/build_conda.yml
- .github/workflows/create_test_conda_env.yml
- docs/contributing_to_doc.rst
- docs/fre_cmor.rst
- docs/index.rst
- docs/setup.rst
- docs/usage.rst
UNO MAS!
idk why but #256 died, i may have to lok at the way i merge recent changes to `main` into my development branches- that the only time unintentional closing occurs...
focusing on `fre cmor` functionality here more explicitly, having lopped off #254, #255, after some good general changes.
see preview of doc page at my [fork's gh-pages](https://ilaflott.github.io/ians_fre_cli/)
code QA
N/A ~~- [ ] I wrote a new test, if applicable~~
N/A ~~- [ ] I ran pytest and inspected it's output~~
N/A ~~- [ ] I ran pylint and attempted to implement some of it's feedback~~
> Update fre cmor doc

- fre/app/regrid_xy/regrid_xy.py
- fre/make/tests/test_create_makefile.py
- fre/pp/checkoutScript.py
- fre/pp/frepp.py
- fre/pp/validate.py
- fre/tests/test_fre_pp_cli.py
- fre/yamltools/combine_yamls.py
- click entry-point adjustments, particularly for `fre pp configure-yaml`
- some `chdir`s that werent needed are removed
- some `chdir`s that ARE needed are un-done by the end of the routine
- a `fre make` tests now re-sets the `os.environ['HOME']` back to what it was before adjustment
- adds a unit test that will catch a mal-functioning click entry-point for `fre pp configure-yaml`
- adds, FINALLY, a functional unit test for `fre pp checkout`
> `fre pp configure-yaml` entry-point for click fix, test

- fre/make/createDocker.py
Updates the `createDockerfile` fremake subcommand to create a short container build script instead of running commands directly.
I also added another level of indents so it'll only create the build script/run if the `if iscontainer` conditional is true like the commands above it. I think it needs the commands above it for the build script to work properly, but I don't really know how multiplatform builds work so let me know if it should be moved back.
This needs #271 in first, which adds the same functionality to run-fremake with container builds.
> add container buildscript creation for `createDockerfile`

- fre/yamltools/combine_yamls.py
The print statement for created combined yaml for post-processing was showing an incorrect location to the combined yaml. This prints the absolute path to the yaml now.
> Fix print statement to reflect full path to combined yaml

- fre/pp/configure_script_xml.py
- fre/pp/frepp.py
- fre/pp/install_script.py
The click decorator function for the install subtool was not being called properly in `install.py`.  Fixed the click decorator function and anywhere else I saw the same issue. 
N/A
>  Fix click decorator calls

- docs/tools/yamltools.rst
- docs/usage/compile.rst
- Updating documentation for `combine-yamls` tool
- Updating fre make quickstart to use null_model example instead of AM5 
-
> Update cli doc

- fre/make/create_compile_script.py
- fre/make/create_docker_script.py
- fre/make/create_makefile_script.py
- fre/make/run_fremake_script.py
If an incorrect platform was passed with the fre make commands, there was a very informative error raised. This fixes the error message to basically say "the platform passed doesn't exists in the platforms.yaml"
>  Fix error message for incorrect platform used

- fre/pp/install_script.py
> Convert bytes to string for proper workflow config comparing (in fre pp install)

- fre/pp/run_script.py
- check to see if the scheduler is already up; if so exit right away with success
- otherwise, sleep 30 seconds, then confirm the scheduler is actually up
- if not, error 30 seconds was chosen based on hand-testing and might have to be adjusted later
#317
~~- [ ] I wrote a new test, if applicable~~ (calls to `cylc` are not yet testable presently)
> Updates to 'fre pp run' to account for delay in starting Cylc scheduler

- fre/cmor/cmor_mixer.py
- fre/fre.py
- fre/tests/test_fre_cli.py
- setup.py
Traditionally, we do not update the package version often, but new updates are re-published to the noaa-gfdl anaconda channel with the same version.
https://anaconda.org/NOAA-GFDL/fre-cli
However, in the last few weeks the publishing pipeline has not updated as expected. So let's bump the minor package version and see if it builds and deploys.
> Update package version to 2025.01.01

- fre/app/freapp.py
- fre/app/generate_time_averages/cdoTimeAverager.py
- fre/app/generate_time_averages/frenctoolsTimeAverager.py
- fre/app/generate_time_averages/frepytoolsTimeAverager.py
- fre/app/generate_time_averages/generate_time_averages.py
- fre/app/generate_time_averages/tests/test_generate_time_averages.py
- fre/app/generate_time_averages/timeAverager.py
Timeaveraging itself is complicated enough!
Standard deviation calculation could be its own tool in the future.
> Remove standard deviation feature from fre pp gen-time-averages

- .github/workflows/create_test_conda_env.yml
- environment.yml
- meta.yaml
Python 3.9 is too old (not receiving security updates) and probably causes fre analysis install issues.
Hand testing showed cylc-uiserver was causing the solver to always use 3.9.
> Require python 3.10 and remove cylc-uiserver as a dependency

- fre/yamltools/pp_info_parser.py
If there was only 1 experiment or analysis yaml listed, there would be a problem with combining yaml information. This was because the experiment and analysis yaml paths were passed in a list but then they were not looped over. 
I just added indexing the first element in the list, if there was only 1 experiment or analysis yaml listed.
> Combine yamls fix

- fre/make/gfdlfremake/targetfre.py
Adds a conditional to turn on link time optimization via mkmf when 'lto' is included in the target. Its used like openmp so is specified in addition to the standard prod/debug/repro name.
relies on this PR to add the mkmf option: https://github.com/NOAA-GFDL/mkmf/pull/77
> add link time optimization option as a target

- fre/app/generate_time_averages/frenctoolsTimeAverager.py
- fre/app/generate_time_averages/tests/test_generate_time_averages.py
expanded fre-cli/fre/app/generate_time_averages/frenctoolsTimeAverager.py to include option for monthly climatology. Functions by breaking apart netcdf input file into monthly chunks, and then recursively running over each of those with a timavg command. after, deletes the folder and new input nc files. leaves behind a folder labeled "monthly_output_files", with the outputs inside being named {Month}_{user requested output name}. Also added several tests.
Monthly climatologies using fre-nctools backend #391
> Monthly climatology.391

- docs/usage/yaml_dev/pp_yaml.rst
- fre/pp/configure_script_xml.py
- fre/pp/edits-template.yaml
- fre/pp/tests/AM5_example/yaml_include/settings.yaml
- fre/yamltools/tests/AM5_example/analysis_yamls/clouds.yaml
- fre/yamltools/tests/AM5_example/analysis_yamls/land.yaml
- fre/yamltools/tests/AM5_example/pp_yamls/settings.yaml
The code, documentation, tests, and templates have been updated in accordance with the changes to the PP yaml format proposed in NOAA-GFDL/gfdl_msd_schemas#28:
- Replace `pp_chunk_a` and `pp_chunk_b` with an array called `pp_chunks`
- Replace `cumulative` and `script_frequency` with `script_type` and `chunk_size` in analysis script configurations.
This should be tested in conjunction with NOAA-GFDL/gfdl_msd_schemas#28 and NOAA-GFDL/fre-workflows#69.
#409
> Updates for proposed changes to PP yaml format

- fre/pp/configure_script_yaml.py
- fre/pp/tests/test_rose_quoting.py
#421 caused 'fre pp configure-yaml' to write incorrect lists to rose-suite.conf. The double quoting is not allowed.
```
PP_CHUNKS='['P1Y']'
```
This update adds a check in `quote_rose_values` for whether the config item is a `list` and if so skips the quoting.
> Do not quote lists in rose-suite.conf

- environment.yml
- meta.yaml
force click version to be less than 8.2.
> hotfix: click 8.2.0 breaks tests

- fre/app/generate_time_averages/tests/test_generate_time_averages.py
- fre/make/tests/compilation/test_run_fremake_builds.py
Cleanup functions for the fremake and generate_time_averages tests
https://github.com/NOAA-GFDL/fre-cli/issues/424
I'm skipping the cleanup for /test_cmor_run_subtool_ppan_only.py for the moment because it's turning out to be a bigger job than I thought - and I'd like to get the smaller unit of functionality stowed away and working before taking a deeper dive into why the cmor tests are getting file locking issues.
> cleanup working for generate_time_averages, run_fremake_builds
