NOAA-GFDL/fre-cli

- README.md
- fre/fre.py
- fre/frepp/config.py
- ideas.md
- issues.md
- meta.yaml
Updating README.md, meta.yaml, adding ideas to ideas.md, and cleaning some comments and code in /fre/
> Documentation

- MANIFEST.in
- fre/frepp/config.py
- meta.yaml
fixed jsonschema issue, should now be able to be run from different directories
> fixed jsonschema issue

- .github/workflows/upload_conda.yml
- fre/yamltools/__init__.py
- fre/yamltools/yamltools.py
added /.github/workflows, with /.github/testflows for files I don't want to test right now, as well as some fre yaml command files for barebone elements
> workflow Github Actions file attempt 

- fre/frepp/checkoutScript.py
- fre/frepp/configureScript.py
- fre/frepp/frepp.py
- fre/frepp/wrapperscript
- renamed config.py to configureScript.py to avoid more confusion and follow better naming conventions (for now)
- added checkoutScript.py
- added checkoutScript.py's functionality into frepp.py
- removed unnecessary imports
> checkout script added and cli functionality implemented

- fre/fre.py
- fre/frepp/configureScriptXML.py
- fre/frepp/frepp.py
- fre/frepp/install.py
- fre/frepp/run.py
- fre/frepp/status.py
- fre/frepp/validate.py
- meta.yaml
fre pp validate
fre pp install
fre pp run
fre pp status
> New pp tools

- fre/frepp/configureScriptYAML.py
- accidentally created the rose-app configurations as directories and not files - fixed this
>  #57 Fix remap and regrid rose-app creation

- fre/make/README-fremake.md
> updating fremake documentation

- fre/pp/configureScriptYAML.py
- fre/pp/ppyaml_test/pp.yaml
- remove optional configurations: just keep default `rose-suite.conf`
>  Update location and print statements for rose config files

- fre/cmor/CMORmixer.py
> Restore cmor-mixer standalone script usage for developers

- fre/make/fremake.py
- fre/make/runFremake.py
Basically just copied the most recent `fremake` script and put it under click decorators, whereas the previous one still used older `fremake` code that didn't use mkTemplatePath
> fre make run-fremake fix

- fre/pp/configure_script_yaml.py
- fre/pp/install.py
- fre/pp/run.py
- fre/pp/status.py
- fre/pp/validate.py
- fre/pp/wrapper.py
> Add back the click decorator for yamlInfo

- .github/workflows/documentation.yml
- docs/conf.py
change the pip install line in `.github/workflows/documentation.yml` to no later than `7.3.7`.
leave other theme option comment in `docs/conf.py` to signal available option for themes.
https://github.com/NOAA-GFDL/fre-cli/issues/124 for tracking this, as this hotfix will likely break in the near-ish future. 
N/A ~~I wrote a new test, if applicable~~
N/A ~~I wrote new instructions/documentation, if applicable~~
N/A ~~I ran pytest and inspected it's output~~
N/A ~~I ran pylint and attempted to implement some of it's feedback~~
> Hotfix doc workflow

- README.md
- docs/subtools.rst
- fre/pp/README.md
> Add.fre.pp.readme

- fre/pp/configure_script_yaml.py
- fre/pp/tests/test_rose_quoting.py
Recent updates to `fre pp configure-yaml` seem to require quotes to pass Cylc validation.
#99
> Include quotes in the rose-suite.conf values

- setup.py
> Update conda package version to 2024.01

- fre/make/README.md
>  #187 Add fremake README back in

- fre/yamltools/README.md
> Update yamltools README.md

- CODE_OF_CONDUCT.md
Created a .md file for a code of conduct that is current under construction.
> added code of conduct for review

- fre/make/gfdlfremake/buildDocker.py
> Add escape character

- fre/catalog/frecatalog.py
Add optional fre catalog builder --slow option (default off)
#183
>  #183 Add optional fre catalog builder --slow option (default off)

- fre/make/gfdlfremake/buildDocker.py
> Fix LD_LIBRARY_PATH env. var. name

- .github/workflows/build_conda.yml
- .github/workflows/create_test_conda_env.yml
- docs/badges.rst
- docs/contributing_to_doc.rst
- docs/developer_usage.rst
- docs/fre_app.rst
- docs/fre_catalog.rst
- docs/fre_cmor.rst
- docs/fre_make.rst
- docs/fre_pp.rst
- docs/fre_yamltools.rst
- docs/index.rst
- docs/setup.rst
- docs/usage.rst
focusing on `fre cmor` functionality here more explicitly, having lopped off #254, #255, after some good general changes.
see preview of doc page at my [fork's gh-pages](https://ilaflott.github.io/ians_fre_cli/)
code QA
N/A ~~- [ ] I wrote a new test, if applicable~~
N/A ~~- [ ] I ran pytest and inspected it's output~~
N/A ~~- [ ] I ran pylint and attempted to implement some of it's feedback~~
> Update `fre cmor` doc

- docs/usage/postprocess.rst
> Some more docs

- docs/usage/yaml_framework.rst
- fre/make/create_checkout_script.py
- fre/make/create_compile_script.py
- fre/make/create_docker_script.py
- fre/make/create_makefile_script.py
- fre/make/gfdlfremake/platformfre.py
- fre/make/run_fremake_script.py
- fre/make/tests/null_example/platforms.yaml
Modifies `getPlatformFromName` to return a dictionary instead of a tuple of stuff. This makes it also easier to remove/add things. 
`fc` and `cc` are no longer required
Schema was updated in https://github.com/NOAA-GFDL/gfdl_msd_schemas/pull/16
Changes will likely needed to the tests after the schema commit is updated
Fixes https://github.com/NOAA-GFDL/fre-cli/issues/283
> Remove fc cc

- fre/make/create_makefile_script.py
- fre/make/gfdlfremake/buildBaremetal.py
> Fix create_makefile_script.py location message for container build

- fre/yamltools/combine_yamls.py
- fre/yamltools/tests/test_combine_yamls.py
> Combine pp yamls even if the first one does not define any components

- README.md
- fre/tests/test_fre_cli.py
- setup.py
Update fre-cli to patch version 2025.01.02
> Patch release 2025.01.02 and documentation

- docs/tools/pp.rst
- fre/pp/frepp.py
- fre/pp/nccheck_script.py
- fre/pp/tests/test_nccheck_script.py
- [ X ] I ran my code
- [ X ] I tried to make my code readable
- [ X ] I tried to comment my code
- [ X ] I wrote a new test, if applicable
- [ X ] I wrote new instructions/documentation, if applicable
- [ X ] I ran pytest and inspected it's output
- [ X ] I ran pylint and attempted to implement some of it's feedback
- [ X ] No print statements; all user-facing info uses logging module
> New subtool: fre pp nccheck

- docs/container.rst
- docs/index.rst
New page on Sphinx site. Exclusively for PPP. 
#345
> #345 Adding Sphinx page for PPP

- fre/pp/configure_script_yaml.py
- fre/pp/tests/AM5_example/am5.yaml
- fre/pp/tests/AM5_example/yaml_include/pp-test.c96_amip.yaml
- fre/pp/tests/AM5_example/yaml_include/pp.c96_amip.yaml
The yaml schema was updated such that:
```
components:
- type: atmos
sources:
- history_file: "atmos_4xdaily"
- history_file: "atmos_8xdaily"
```
We needed to get the sources in order to write rose-apps correctly (even though we're going to try to get rid of them soon)
n/a
> Fix rose apps

- docs/setup.rst
- fre/tests/test_fre_cli.py
- setup.py
> Update package release and corresponding tests to 2025.02

- fre/pp/frepp.py
- fre/pp/split_netcdf.py
Merging in changes along the main development branch with a change in what/how to expose functions in split_netcdf to users
https://github.com/NOAA-GFDL/fre-cli/pull/402#issuecomment-2825398253
Still part of a draft pull request once it's merged in - doesn't have to run yet.
> 394.split.netcdf.cew

- LICENSE.md
- README.md
- meta.yaml
Changes the license from LGPL to apache 2.0
#404
> License update

- fre/pp/ppval_script.py
> Minor logic correction

- fre/tests/test_fre_cli.py
- setup.py
Updated fre version for when we are ready to release (one less thing to do later)
>  Update fre-version for whenever we are ready

- fre/app/freapp.py
- fre/app/regrid_xy/regrid_xy.py
- fre/app/regrid_xy/tests/test_regrid_xy.py
- fre/tests/test_fre_app_cli.py
Working fre-cli version of regrid-xy wrapper.
Hand tested successfully.
needed for https://github.com/NOAA-GFDL/fre-workflows/pull/75
> Regridding updates from a checkpoint

- fre/cmor/tests/test_cmor_run_subtool.py
- fre/cmor/tests/test_cmor_run_subtool_ppan_only.py
- fre/pp/split_netcdf_script.py
- fre/tests/test_fre_cmor_cli.py
One of the tests in fre/tests/test_fre_cmor_cli.py is skipped when running on the workstations to avoid trying to write to /archive
This references issue #423
> CMORwrap: 423.mkdir.archive

- .github/workflows/build_conda.yml
- .github/workflows/create_test_conda_env.yml
- .github/workflows/publish_conda.yml
- .gitmodules
- fre/make/create_compile_script.py
- fre/make/run_fremake_script.py
- meta.yaml
- put mkmf submodule under `fre` 
- add mkmf path to PATH in `meta.yaml`
- could also help too: https://github.com/NOAA-GFDL/mkmf/blob/conda_package/meta.yaml (thanks Ian and Chris)
#369
> 369.fre-cli mkmf dependency

- README.md
- docs/for-maintainers.rst
- docs/index.rst
- fre/tests/test_fre_cli.py
- setup.py
> Updated setup.py and tests with 2025.04

- docs/tools/listtools.rst
- docs/tools/make.rst
- docs/tools/yamltools.rst
- docs/usage/build_fms_model.rst
- docs/usage/yaml_dev/platforms_yaml.rst
- fre/tests/test_fre_make_cli.py
Update fre make guide, quickstart, and subtool doc for updated subtool names
#459
>  docs:  #459 Update fre make documentation for subtool names (guides and quickstarts)
